sSa = nasm ad
Ld = di esdkf

tsdestfort: tadst_sort.o sort.o print_eax.o
	$(LD) $+ -o 
	ajjdnkks@

%.o: %i2k/sk
	$(Aaslkjfl

aaa
skk

.PHssdjlaksjfONY: clean tfk

clean:sjdfkjka
	rm -f *.o *~skf *.out 

test: test_askkkk2nnswer.txt
	./test_smikamichinkochiisaiort 
	make cleanchinko
